//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace UploadingAndRetrivingImages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }

        [DisplayName("Student Name")]
        [Required(ErrorMessage = "Student name is requierd!!")]
        public string name { get; set; }

        [DisplayName("Student Claess")]
        [Required(ErrorMessage = "Student class is requierd!!")]
        public int standard { get; set; }

        [DisplayName("Choose Image")]
        public string image_path { get; set; }

        public HttpPostedFileBase ImageFile{ get; set; }
    }
}
