//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace CrudApplicationWithImageInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }

        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Employee name is requiered !!")]
        public string name { get; set; }

        [DisplayName("Employee Designation")]
        [Required(ErrorMessage = "Employee designation is requiered !!")]
        public string designation { get; set; }

        [DisplayName("Employee Image")]
        public string image_path { get; set; }

        public HttpPostedFileBase ImageFile{ get; set; }
    }
}
